using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ObjectStoreE
{
    public interface IConvertable
    {
        /// <summary>
        /// Converts the object to a region
        /// </summary>
        /// <param name="regionName">The name the region should have</param>
        /// <returns>A region that can be parsed by the <see cref="LoadByRegion(Region)"/> method</returns>
        public Region ConvertToRegion(Automatic.ConversionContext? automaticConversionContext);

        /// <summary>
        /// Recreate the object based on the region input. When this is called, the object is uninitialized.
        /// </summary>
        /// <param name="region">The region generated by <see cref="ConvertToRegion(string)"/> to recreate the object state</param>
        public void LoadByRegion(Region region);
    }
}
